[providers]
php = true

[variables]
NIXPACKS_PHP_VERSION = "8.3"

[start]
cmd = "touch database/database.sqlite && php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
